site_name: s0mbr4's space
nav:
    - Home: index.md
    - picoCTF: picoCTF.md 
    
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep purple
      accent: teal
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: deep purple

plugins:
  - social

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Ninioluwa
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Ninioluwa_O
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ninioluwa/

copyright: |
  &copy; 2023 <a href="https://github.com/Ninioluwa"  target="_blank" rel="noopener">Ninioluwa</a>
